# Generated by Django 5.2.7 on 2025-10-07 13:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ballot_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ballot', to='elections.election')),
            ],
            options={
                'db_table': 'ballot',
            },
        ),
        migrations.CreateModel(
            name='BallotCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.ballot')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.candidate')),
            ],
            options={
                'db_table': 'ballot_candidate',
                'ordering': ['order'],
                'unique_together': {('ballot', 'candidate')},
            },
        ),
        migrations.AddField(
            model_name='ballot',
            name='candidates',
            field=models.ManyToManyField(through='voting.BallotCandidate', to='elections.candidate'),
        ),
        migrations.CreateModel(
            name='VotingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned'), ('error', 'Error')], default='started', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.election')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_sessions', to='authentication.voter')),
            ],
            options={
                'db_table': 'voting_session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('encrypted_vote_data', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='elections.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='elections.election')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='authentication.voter')),
            ],
            options={
                'db_table': 'vote',
                'ordering': ['-timestamp'],
                'unique_together': {('voter', 'election')},
            },
        ),
    ]
