# Generated by Django 5.2.7 on 2025-10-08 08:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_delete_otpverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text="Phone number must be in format: '+999999999'. Up to 15 digits allowed.", max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voter_id',
            field=models.CharField(help_text='10-character alphanumeric voter ID provided by voter', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voters_card_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
