# Generated by Django 5.2.7 on 2025-10-08 10:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_phone_number_alter_voter_voter_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text="Phone number must be in format: '+999999999'. Up to 15 digits allowed.", max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number can contain digits, +, -, and spaces.', regex='^[0-9+\\-\\s]+$')]),
        ),
    ]
