# Generated by Django 5.2.7 on 2025-10-09 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='biometric_data',
        ),
    ]
