# Generated by Django 5.2.7 on 2025-12-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_user_biometric_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='can_vote',
            field=models.BooleanField(default=False),
        ),
    ]
