# Generated by Django 5.2.7 on 2025-10-07 13:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('incident_type', models.CharField(choices=[('voter_intimidation', 'Voter Intimidation'), ('ballot_stuffing', 'Ballot Stuffing'), ('technical_issue', 'Technical Issue'), ('violence', 'Violence'), ('bribery', 'Bribery'), ('equipment_malfunction', 'Equipment Malfunction'), ('unauthorized_access', 'Unauthorized Access'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to='authentication.inecofficial')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_reports', to=settings.AUTH_USER_MODEL)),
                ('voter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='authentication.voter')),
            ],
            options={
                'db_table': 'incident_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('evidence_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document')], max_length=10)),
                ('file', models.FileField(upload_to='incident_evidence/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('file_hash', models.CharField(blank=True, max_length=64)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='incidents.incidentreport')),
            ],
            options={
                'db_table': 'incident_evidence',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('action_type', models.CharField(choices=[('investigation_started', 'Investigation Started'), ('evidence_collected', 'Evidence Collected'), ('witness_interviewed', 'Witness Interviewed'), ('corrective_action', 'Corrective Action Taken'), ('case_closed', 'Case Closed'), ('escalated', 'Escalated to Higher Authority')], max_length=30)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='incidents.incidentreport')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.inecofficial')),
            ],
            options={
                'db_table': 'incident_response',
                'ordering': ['-created_at'],
            },
        ),
    ]
